Brought sunbird code up to date with firefox code

diff --git a/calendar/sunbird/app/mozilla.in b/calendar/sunbird/app/mozilla.in
--- a/calendar/sunbird/app/mozilla.in
+++ b/calendar/sunbird/app/mozilla.in
@@ -16,7 +16,7 @@
 # Reserved.
 #
 
-## $Id: mozilla.in,v 1.3 2004/02/11 15:11:51 mostafah%oeone.com Exp $
+## $Id: mozilla.in,v 1.4 2004/04/07 18:55:07 mostafah%oeone.com Exp $
 ## 
 ## Usage:
 ##
@@ -28,6 +28,46 @@
 ## The script will setup all the environment voodoo needed to make
 ## the mozilla-bin binary to work.
 ##
+
+moz_pis_startstop_scripts()
+{
+  MOZ_USER_DIR="%MOZ_USER_DIR%"
+  # MOZ_PIS_ is the name space for "Mozilla Plugable Init Scripts"
+  # These variables and there meaning are specified in
+  # mozilla/xpfe/bootstrap/init.d/README
+  MOZ_PIS_API=2
+  MOZ_PIS_MOZBINDIR="${dist_bin}"
+  MOZ_PIS_SESSION_PID="$$"
+  MOZ_PIS_USER_DIR="${MOZ_USER_DIR}"
+  export MOZ_PIS_API MOZ_PIS_MOZBINDIR MOZ_PIS_SESSION_PID MOZ_PIS_USER_DIR
+  
+  case "${1}" in
+    "start")
+      for curr_pis in "${dist_bin}/init.d"/S* "${HOME}/${MOZ_USER_DIR}/init.d"/S* ; do
+        if [ -x "${curr_pis}" ] ; then
+          case "${curr_pis}" in
+            *.sh) .  "${curr_pis}"         ;;
+            *)       "${curr_pis}" "start" ;;
+          esac
+        fi
+      done
+      ;;
+    "stop")
+      for curr_pis in "${HOME}/${MOZ_USER_DIR}/init.d"/K* "${dist_bin}/init.d"/K* ; do
+        if [ -x "${curr_pis}" ] ; then
+          case "${curr_pis}" in
+            *.sh) . "${curr_pis}"        ;;
+            *)      "${curr_pis}" "stop" ;;
+          esac
+        fi
+      done
+      ;;
+    *)
+      echo 1>&2 "$0: Internal error in moz_pis_startstop_scripts."
+      exit 1
+      ;;
+  esac
+}
 
 #uncomment for debugging
 #set -x
@@ -77,7 +117,7 @@ fi
 script_args=""
 moreargs=""
 debugging=0
-MOZILLA_BIN="mozilla-bin"
+MOZILLA_BIN="%MOZILLA-BIN%"
 
 if [ "$OSTYPE" = "beos" ]; then
   mimeset -F $MOZILLA_BIN
@@ -87,7 +127,7 @@ while [ $# -gt 0 ]
 do
   case "$1" in
     -p | -pure)
-      MOZILLA_BIN="mozilla-bin.pure"
+      MOZILLA_BIN="%MOZILLA-BIN%.pure"
       shift
       ;;
     -g | --debug)
@@ -108,8 +148,19 @@ done
 
 export MRE_HOME
 eval "set -- $moreargs"
+
+## Start addon scripts
+moz_pis_startstop_scripts "start"
+
 if [ $debugging = 1 ]
 then
   echo $dist_bin/run-mozilla.sh $script_args $dist_bin/$MOZILLA_BIN "$@"
 fi
-exec "$dist_bin/run-mozilla.sh" $script_args "$dist_bin/$MOZILLA_BIN" "$@"
+"$dist_bin/run-mozilla.sh" $script_args "$dist_bin/$MOZILLA_BIN" "$@"
+exitcode=$?
+
+## Stop addon scripts
+moz_pis_startstop_scripts "stop"
+
+exit $exitcode
+# EOF.
