Fix unquoted string in OJI/JAVA test.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1361,10 +1361,11 @@ MOZ_ARG_ENABLE_BOOL(java,
 [  --enable-java           Enable use of java applets (untested)],
   [MOZ_JAVA=1 FULL_STATIC_BUILD= NO_SHARED_LIB=])
 
-if test ${MOZ_OJI} -eq 1 -a ${MOZ_JAVA} -eq 1
+if test "$MOZ_OJI" -eq 1 -a "$MOZ_JAVA" -eq 1
 then
-	echo "configure: error: Simultaneous use of --enable-java and --enable-oji is no longer supported." 1>&2
-	exit 1
+  echo "configure: error: Simultaneous use of --enable-java and\
+        --enable-oji is no longer supported." 1>&2
+  exit 1
 fi
 
 MOZ_ARG_ENABLE_BOOL(mail-compose,
