Automated update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13471,6 +13471,7 @@ fi
 
 if test "$SKIP_IDL_CHECK" = "no"
 then
+    _LIBIDL_FOUND=
     if test "$MOZ_ENABLE_GTK2"; then
         
   succeeded=no
@@ -13479,7 +13480,7 @@ then
     # Extract the first word of "pkg-config", so it can be a program name with args.
 set dummy pkg-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:13483: checking for $ac_word" >&5
+echo "configure:13484: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PKG_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -13523,19 +13524,19 @@ fi
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
         echo $ac_n "checking for libIDL-2.0 >= 0.8.0""... $ac_c" 1>&6
-echo "configure:13527: checking for libIDL-2.0 >= 0.8.0" >&5
+echo "configure:13528: checking for libIDL-2.0 >= 0.8.0" >&5
 
         if $PKG_CONFIG --exists "libIDL-2.0 >= 0.8.0" ; then
             echo "$ac_t""yes" 1>&6
             succeeded=yes
 
             echo $ac_n "checking LIBIDL_CFLAGS""... $ac_c" 1>&6
-echo "configure:13534: checking LIBIDL_CFLAGS" >&5
+echo "configure:13535: checking LIBIDL_CFLAGS" >&5
             LIBIDL_CFLAGS=`$PKG_CONFIG --cflags "libIDL-2.0 >= 0.8.0"`
             echo "$ac_t""$LIBIDL_CFLAGS" 1>&6
 
             echo $ac_n "checking LIBIDL_LIBS""... $ac_c" 1>&6
-echo "configure:13539: checking LIBIDL_LIBS" >&5
+echo "configure:13540: checking LIBIDL_LIBS" >&5
             LIBIDL_LIBS=`$PKG_CONFIG --libs "libIDL-2.0 >= 0.8.0"`
             echo "$ac_t""$LIBIDL_LIBS" 1>&6
         else
@@ -13544,7 +13545,7 @@ echo "configure:13539: checking LIBIDL_LIBS" >&5
             ## If we have a custom action on failure, don't print errors, but 
             ## do set a variable so people can do so.
             LIBIDL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libIDL-2.0 >= 0.8.0"`
-            
+            echo $LIBIDL_PKG_ERRORS
         fi
 
         
@@ -13556,12 +13557,13 @@ echo "configure:13539: checking LIBIDL_LIBS" >&5
   fi
 
   if test $succeeded = yes; then
-     :
+     _LIBIDL_FOUND=1
   else
-     _LIBIDL_NOT_FOUND=1
+     { echo "configure: error: Library requirements (libIDL-2.0 >= 0.8.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." 1>&2; exit 1; }
   fi
 
-    else
+    fi
+    if test -z "$_LIBIDL_FOUND"; then
         # Check whether --with-libIDL-prefix or --without-libIDL-prefix was given.
 if test "${with_libIDL_prefix+set}" = set; then
   withval="$with_libIDL_prefix"
@@ -13655,7 +13657,7 @@ fi
   # Extract the first word of "glib-config", so it can be a program name with args.
 set dummy glib-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:13659: checking for $ac_word" >&5
+echo "configure:13661: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GLIB_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -13690,7 +13692,7 @@ fi
 
   min_glib_version=1.2.0
   echo $ac_n "checking for GLIB - version >= $min_glib_version""... $ac_c" 1>&6
-echo "configure:13694: checking for GLIB - version >= $min_glib_version" >&5
+echo "configure:13696: checking for GLIB - version >= $min_glib_version" >&5
   no_glib=""
   if test "$GLIB_CONFIG" = "no" ; then
     no_glib=yes
@@ -13713,7 +13715,7 @@ echo "configure:13694: checking for GLIB - version >= $min_glib_version" >&5
   echo $ac_n "cross compiling; assumed OK... $ac_c"
 else
   cat > conftest.$ac_ext <<EOF
-#line 13717 "configure"
+#line 13719 "configure"
 #include "confdefs.h"
 
 #include <glib.h>
@@ -13789,7 +13791,7 @@ main ()
 }
 
 EOF
-if { (eval echo configure:13793: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:13795: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -13823,7 +13825,7 @@ fi
           CFLAGS="$CFLAGS $GLIB_CFLAGS"
           LIBS="$LIBS $GLIB_LIBS"
           cat > conftest.$ac_ext <<EOF
-#line 13827 "configure"
+#line 13829 "configure"
 #include "confdefs.h"
 
 #include <glib.h>
@@ -13833,7 +13835,7 @@ int main() {
  return ((glib_major_version) || (glib_minor_version) || (glib_micro_version)); 
 ; return 0; }
 EOF
-if { (eval echo configure:13837: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:13839: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
    echo "*** The test program compiled, but did not run. This usually means"
           echo "*** that the run-time linker is not finding GLIB or finding the wrong"
@@ -13877,7 +13879,7 @@ rm -f conftest*
   # Extract the first word of "libIDL-config", so it can be a program name with args.
 set dummy libIDL-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:13881: checking for $ac_word" >&5
+echo "configure:13883: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_LIBIDL_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -13912,7 +13914,7 @@ fi
 
   min_libIDL_version=$LIBIDL_VERSION
   echo $ac_n "checking for libIDL - version >= $min_libIDL_version""... $ac_c" 1>&6
-echo "configure:13916: checking for libIDL - version >= $min_libIDL_version" >&5
+echo "configure:13918: checking for libIDL - version >= $min_libIDL_version" >&5
   no_libIDL=""
   if test "$LIBIDL_CONFIG" = "no" ; then
     no_libIDL=yes
@@ -13939,7 +13941,7 @@ echo "configure:13916: checking for libIDL - version >= $min_libIDL_version" >&5
   echo $ac_n "cross compiling; assumed OK... $ac_c"
 else
   cat > conftest.$ac_ext <<EOF
-#line 13943 "configure"
+#line 13945 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -14025,7 +14027,7 @@ main ()
 }
 
 EOF
-if { (eval echo configure:14029: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:14031: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -14043,7 +14045,7 @@ fi
   fi
   if test "x$no_libIDL" = x ; then
      echo "$ac_t""yes" 1>&6
-     :     
+     _LIBIDL_FOUND=1     
   else
      echo "$ac_t""no" 1>&6
      if test "$LIBIDL_CONFIG" = "no" ; then
@@ -14059,7 +14061,7 @@ fi
           CFLAGS="$CFLAGS $LIBIDL_CFLAGS"
           LIBS="$LIBS $LIBIDL_LIBS"
           cat > conftest.$ac_ext <<EOF
-#line 14063 "configure"
+#line 14065 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -14070,7 +14072,7 @@ int main() {
  return IDL_get_libver_string ? 1 : 0; 
 ; return 0; }
 EOF
-if { (eval echo configure:14074: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:14076: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
    echo "*** The test program compiled, but did not run. This usually means"
           echo "*** that the run-time linker is not finding libIDL or finding the wrong"
@@ -14097,20 +14099,20 @@ rm -f conftest*
      fi
      LIBIDL_CFLAGS=""
      LIBIDL_LIBS=""
-     _LIBIDL_NOT_FOUND=1
+     :
   fi
   
   
   rm -f conf.libIDLtest
 
     fi
-                    if test -n "$_LIBIDL_NOT_FOUND" && test -z "$CROSS_COMPILE"; then
+                    if test -z "$_LIBIDL_FOUND" && test -z "$CROSS_COMPILE"; then
         for ac_prog in $ORBIT_CONFIG orbit-config
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:14114: checking for $ac_word" >&5
+echo "configure:14116: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_ORBIT_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -14153,10 +14155,10 @@ done
             LIBIDL_CFLAGS="$_ORBIT_INC_PATH"
             LIBIDL_LIBS="$_ORBIT_LIB_PATH -lIDL -lglib"
             LIBIDL_CONFIG=
-            _LIBIDL_NOT_FOUND=
+            _LIBIDL_FOUND=1
         fi
     fi
-    if test -n "$_LIBIDL_NOT_FOUND"; then
+    if test -z "$_LIBIDL_FOUND"; then
         { echo "configure: error: libIDL not found.
         libIDL $LIBIDL_VERSION or higher is required." 1>&2; exit 1; }
     fi
@@ -14232,7 +14234,7 @@ fi
   # Extract the first word of "glib-config", so it can be a program name with args.
 set dummy glib-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:14236: checking for $ac_word" >&5
+echo "configure:14238: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GLIB_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -14267,7 +14269,7 @@ fi
 
   min_glib_version=${GLIB_VERSION}
   echo $ac_n "checking for GLIB - version >= $min_glib_version""... $ac_c" 1>&6
-echo "configure:14271: checking for GLIB - version >= $min_glib_version" >&5
+echo "configure:14273: checking for GLIB - version >= $min_glib_version" >&5
   no_glib=""
   if test "$GLIB_CONFIG" = "no" ; then
     no_glib=yes
@@ -14290,7 +14292,7 @@ echo "configure:14271: checking for GLIB - version >= $min_glib_version" >&5
   echo $ac_n "cross compiling; assumed OK... $ac_c"
 else
   cat > conftest.$ac_ext <<EOF
-#line 14294 "configure"
+#line 14296 "configure"
 #include "confdefs.h"
 
 #include <glib.h>
@@ -14366,7 +14368,7 @@ main ()
 }
 
 EOF
-if { (eval echo configure:14370: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:14372: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -14400,7 +14402,7 @@ fi
           CFLAGS="$CFLAGS $GLIB_CFLAGS"
           LIBS="$LIBS $GLIB_LIBS"
           cat > conftest.$ac_ext <<EOF
-#line 14404 "configure"
+#line 14406 "configure"
 #include "confdefs.h"
 
 #include <glib.h>
@@ -14410,7 +14412,7 @@ int main() {
  return ((glib_major_version) || (glib_minor_version) || (glib_micro_version)); 
 ; return 0; }
 EOF
-if { (eval echo configure:14414: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:14416: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
    echo "*** The test program compiled, but did not run. This usually means"
           echo "*** that the run-time linker is not finding GLIB or finding the wrong"
@@ -14553,14 +14555,14 @@ ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$a
 cross_compiling=$ac_cv_prog_cc_cross
 
     cat > conftest.$ac_ext <<EOF
-#line 14557 "configure"
+#line 14559 "configure"
 #include "confdefs.h"
 #include <gmodule.h>
 int main() {
  int x = 1; x++; 
 ; return 0; }
 EOF
-if { (eval echo configure:14564: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:14566: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   :
 else
   echo "configure: failed program was:" >&5
