Sigh.  This should be a warning for now, not an error condition

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2641,7 +2641,7 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-for ac_prog in gawk mawk nawk awk
+for ac_prog in mawk gawk nawk awk
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2917,7 +2917,7 @@ test -n "$ZIP" && break
 done
 
 if test -z "$ZIP"; then
-    { echo "configure: error: zip not found in \$PATH. Disabling jar packaging" 1>&2; exit 1; }
+    echo "configure: warning: zip not found in \$PATH. Disabling jar packaging" 1>&2
     MOZ_DISABLE_JAR_PACKAGING=1
 fi
 # Extract the first word of "makedepend", so it can be a program name with args.
