Automated update from host egg

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17989,6 +17989,94 @@ fi
 
 
 
+MOZ_PYTHON=
+MOZ_PYTHON_PREFIX=
+MOZ_PYTHON_INCLUDES=
+MOZ_PYTHON_LIBS=
+MOZ_PYTHON_VER=
+MOZ_PYTHON_VER_DOTTED=
+MOZ_PYTHON_DEBUG_SUFFIX=
+MOZ_PYTHON_DLL_SUFFIX=
+if test `echo "$MOZ_EXTENSIONS" | grep -c python/xpcom` -ne 0; then
+        if test -z "$PYTHON"; then
+        # Extract the first word of "python", so it can be a program name with args.
+set dummy python; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:18006: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_PYTHON'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$PYTHON" in
+  /*)
+  ac_cv_path_PYTHON="$PYTHON" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_PYTHON="$PYTHON" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_PYTHON="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_PYTHON" && ac_cv_path_PYTHON=":"
+  ;;
+esac
+fi
+PYTHON="$ac_cv_path_PYTHON"
+if test -n "$PYTHON"; then
+  echo "$ac_t""$PYTHON" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+    fi
+    if test "$OS_ARCH" = "WINNT"; then
+                PYTHON=`cygpath -t mixed $PYTHON`
+    fi
+    if test ! -x "$PYTHON"; then
+        { echo "configure: error: Could not find Python - please adjust your PATH, or set PYTHON." 1>&2; exit 1; }
+    fi
+    MOZ_PYTHON=$PYTHON
+        MOZ_PYTHON_VER=`$PYTHON -c "import sys;print '%d%d' % sys.version_info[0:2]"`
+    MOZ_PYTHON_VER_DOTTED=`$PYTHON -c "import sys;print '%d.%d' % sys.version_info[0:2]"`
+        MOZ_PYTHON_PREFIX=`$PYTHON -c "import sys; print sys.prefix"`
+        if test "$OS_ARCH" = "WINNT"; then
+        MOZ_PYTHON_PREFIX=`cygpath -t mixed $MOZ_PYTHON_PREFIX`
+                                MOZ_PYTHON_DLL_SUFFIX=.pyd
+        MOZ_PYTHON_INCLUDES="\"-I$MOZ_PYTHON_PREFIX/include\" \"-I$MOZ_PYTHON_PREFIX/PC\""
+        MOZ_PYTHON_LIBS="\"/libpath:$MOZ_PYTHON_PREFIX/PCBuild\" \"/libpath:$MOZ_PYTHON_PREFIX/libs\""
+    else
+                MOZ_PYTHON_DLL_SUFFIX=$DLL_SUFFIX
+        PYTHON_INCLUDE_SRC=$MOZ_PYTHON_PREFIX/include/python$MOZ_PYTHON_VER_DOTTED
+        PYTHON_LIB_SRC=`$PYTHON  -c 'from distutils import sysconfig; print sysconfig.get_config_var("LIBPL")'`
+        if test ! -f $PYTHON_INCLUDE_SRC/Python.h; then
+            { echo "configure: error: Include directory $PYTHON_INCLUDE_SRC not found or does not contain development headers" 1>&2; exit 1; }
+        fi
+        MOZ_PYTHON_INCLUDES="-I$PYTHON_INCLUDE_SRC"
+        MOZ_PYTHON_LIBS="-L$PYTHON_LIB_SRC -lpython$MOZ_PYTHON_VER_DOTTED"
+    fi
+        if test "$OS_ARCH" = "WINNT" && test -n "$MOZ_DEBUG"; then
+        MOZ_PYTHON_DEBUG_SUFFIX="_d"
+    else
+        MOZ_PYTHON_DEBUG_SUFFIX=
+    fi
+    echo "$ac_t""Building PyXPCOM using Python-$MOZ_PYTHON_VER_DOTTED from $MOZ_PYTHON_PREFIX" 1>&6
+fi
+
+
+
+
+
+
+
+
+
 # Check whether --enable-profilesharing or --disable-profilesharing was given.
 if test "${enable_profilesharing+set}" = set; then
   enableval="$enable_profilesharing"
@@ -18178,14 +18266,14 @@ ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$a
 cross_compiling=$ac_cv_prog_cc_cross
 
     cat > conftest.$ac_ext <<EOF
-#line 18182 "configure"
+#line 18270 "configure"
 #include "confdefs.h"
 #include <gmodule.h>
 int main() {
  int x = 1; x++; 
 ; return 0; }
 EOF
-if { (eval echo configure:18189: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:18277: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   :
 else
   echo "configure: failed program was:" >&5
@@ -18479,7 +18567,7 @@ if test -n "$MOZ_X11"; then
                 _SAVE_CFLAGS=$CFLAGS
     CFLAGS="$CFLAGS $XCFLAGS"
     cat > conftest.$ac_ext <<EOF
-#line 18483 "configure"
+#line 18571 "configure"
 #include "confdefs.h"
 
         #include <stdio.h>
@@ -18495,7 +18583,7 @@ int main() {
     
 ; return 0; }
 EOF
-if { (eval echo configure:18499: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:18587: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   :
 else
   echo "configure: failed program was:" >&5
@@ -19094,6 +19182,15 @@ s%@MOZ_TREE_CAIRO@%$MOZ_TREE_CAIRO%g
 s%@MOZ_CAIRO_CFLAGS@%$MOZ_CAIRO_CFLAGS%g
 s%@MOZ_CAIRO_LIBS@%$MOZ_CAIRO_LIBS%g
 s%@MOZ_XUL@%$MOZ_XUL%g
+s%@PYTHON@%$PYTHON%g
+s%@MOZ_PYTHON@%$MOZ_PYTHON%g
+s%@MOZ_PYTHON_PREFIX@%$MOZ_PYTHON_PREFIX%g
+s%@MOZ_PYTHON_INCLUDES@%$MOZ_PYTHON_INCLUDES%g
+s%@MOZ_PYTHON_LIBS@%$MOZ_PYTHON_LIBS%g
+s%@MOZ_PYTHON_VER@%$MOZ_PYTHON_VER%g
+s%@MOZ_PYTHON_VER_DOTTED@%$MOZ_PYTHON_VER_DOTTED%g
+s%@MOZ_PYTHON_DEBUG_SUFFIX@%$MOZ_PYTHON_DEBUG_SUFFIX%g
+s%@MOZ_PYTHON_DLL_SUFFIX@%$MOZ_PYTHON_DLL_SUFFIX%g
 s%@NECKO_PROTOCOLS@%$NECKO_PROTOCOLS%g
 s%@NECKO_DISK_CACHE@%$NECKO_DISK_CACHE%g
 s%@NECKO_SMALL_BUFFERS@%$NECKO_SMALL_BUFFERS%g
