Automated update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 
 # Read in '.mozconfig' script to set the initial options.
-# See the load-mozconfig.sh script for more details.
+# See the mozconfig2configure script for more details.
 _AUTOCONF_TOOLS_DIR=`dirname $0`/./build/autoconf
 . $_AUTOCONF_TOOLS_DIR/mozconfig2configure
 
@@ -9690,34 +9690,35 @@ EOF
 fi
 
 
-if test "$MOZ_DEBUG"
-then
-  DETECT_WEBSHELL_LEAKS=1
-fi
-
+echo $ac_n "checking webshell leaks option""... $ac_c" 1>&6
+echo "configure:9695: checking webshell leaks option" >&5
 # Check whether --enable-detect-webshell-leaks or --disable-detect-webshell-leaks was given.
 if test "${enable_detect_webshell_leaks+set}" = set; then
   enableval="$enable_detect_webshell_leaks"
-   if test "$enableval" = "yes"; then
-        DETECT_WEBSHELL_LEAKS=1
-      else
-        if test "$enableval" = "no"; then
-          echo "*** Disabling detect webshell leaks code."
-          DETECT_WEBSHELL_LEAKS=""
-        fi
-      fi
-     
-
+  if test "$enableval" = "yes"; then
+     echo "$ac_t""on (user enabled)" 1>&6
+    DETECT_WEBSHELL_LEAKS=1 
+  elif test "$enableval" = "no"; then
+     echo "$ac_t""off (user disabled)" 1>&6 
+  else
+    { echo "configure: error: Option, detect-webshell-leaks, does not take an argument ($enableval)." 1>&2; exit 1; }
+  fi
+else
+   if test "$MOZ_DEBUG"; then
+      echo "$ac_t""on (debug build)" 1>&6
+      DETECT_WEBSHELL_LEAKS=1 
+    else
+      echo "$ac_t""off (non-debug build)" 1>&6
+    fi
 fi
 
 
-if test "$DETECT_WEBSHELL_LEAKS"
-then
-  echo "*** Enabling detect webshell leaks code."
+if test "$DETECT_WEBSHELL_LEAKS"; then
   cat >> confdefs.h <<\EOF
 #define DETECT_WEBSHELL_LEAKS 1
 EOF
-
+ 
+  
 fi
 
 # Check whether --enable-double-buffer or --disable-double-buffer was given.
@@ -9764,7 +9765,7 @@ if test "${enable_efence+set}" = set; then
   enableval="$enable_efence"
   if test "$enableval" = "yes"; then
     echo $ac_n "checking for malloc in -lefence""... $ac_c" 1>&6
-echo "configure:9768: checking for malloc in -lefence" >&5
+echo "configure:9769: checking for malloc in -lefence" >&5
 ac_lib_var=`echo efence'_'malloc | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -9772,7 +9773,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lefence  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 9776 "configure"
+#line 9777 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -9783,7 +9784,7 @@ int main() {
 malloc()
 ; return 0; }
 EOF
-if { (eval echo configure:9787: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:9788: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -9819,7 +9820,7 @@ fi
 
 
 echo $ac_n "checking for cplus_demangle in -liberty""... $ac_c" 1>&6
-echo "configure:9823: checking for cplus_demangle in -liberty" >&5
+echo "configure:9824: checking for cplus_demangle in -liberty" >&5
 ac_lib_var=`echo iberty'_'cplus_demangle | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -9827,7 +9828,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-liberty "-liberty" $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 9831 "configure"
+#line 9832 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -9838,7 +9839,7 @@ int main() {
 cplus_demangle()
 ; return 0; }
 EOF
-if { (eval echo configure:9842: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:9843: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -10049,7 +10050,7 @@ case "$target" in
 	    # Extract the first word of "makeC++SharedLib_r", so it can be a program name with args.
 set dummy makeC++SharedLib_r; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:10053: checking for $ac_word" >&5
+echo "configure:10054: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_AIX_SHLIB_BIN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -10094,7 +10095,6 @@ fi
 	
 	;;
 esac
-
 
 
 
@@ -11027,6 +11027,7 @@ s%@LIBOBJS@%$LIBOBJS%g
 s%@MOZ_MAIL_NEWS@%$MOZ_MAIL_NEWS%g
 s%@COMPILER_DEPEND@%$COMPILER_DEPEND%g
 s%@MDDEPDIR@%$MDDEPDIR%g
+s%@DETECT_WEBSHELL_LEAKS@%$DETECT_WEBSHELL_LEAKS%g
 s%@MOZ_DEMANGLE_SYMBOLS@%$MOZ_DEMANGLE_SYMBOLS%g
 s%@AIX_SHLIB_BIN@%$AIX_SHLIB_BIN%g
 s%@AR_FLAGS@%$AR_FLAGS%g
@@ -11052,7 +11053,6 @@ s%@GC_LEAK_DETECTOR@%$GC_LEAK_DETECTOR%g
 s%@MOZ_LOG_REFCNT@%$MOZ_LOG_REFCNT%g
 s%@MOZ_LEAKY@%$MOZ_LEAKY%g
 s%@MOZ_JPROF@%$MOZ_JPROF%g
-s%@DETECT_WEBSHELL_LEAKS@%$DETECT_WEBSHELL_LEAKS%g
 s%@MOZ_INSURE@%$MOZ_INSURE%g
 s%@MOZ_INSURE_DIRS@%$MOZ_INSURE_DIRS%g
 s%@MOZ_INSURE_EXCLUDE_DIRS@%$MOZ_INSURE_EXCLUDE_DIRS%g
