Automated update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7610,7 +7610,7 @@ if test "${enable_async_dns+set}" = set; then
 fi
 
 
-MOZ_BUILD_NSPR=1
+MOZ_NATIVE_NSPR=
 
 MOZ_BUILD_XPFE=1
 
@@ -8057,7 +8057,6 @@ fi
 
 
 
-
 # Check whether --with-jpeg or --without-jpeg was given.
 if test "${with_jpeg+set}" = set; then
   withval="$with_jpeg"
@@ -8074,7 +8073,7 @@ if test "$JPEG_DIR" = no; then
     SYSTEM_JPEG=
 else
     echo $ac_n "checking for jpeg_destroy_compress in -ljpeg""... $ac_c" 1>&6
-echo "configure:8078: checking for jpeg_destroy_compress in -ljpeg" >&5
+echo "configure:8077: checking for jpeg_destroy_compress in -ljpeg" >&5
 ac_lib_var=`echo jpeg'_'jpeg_destroy_compress | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8082,7 +8081,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ljpeg $JPEG_LIBS $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8086 "configure"
+#line 8085 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8093,7 +8092,7 @@ int main() {
 jpeg_destroy_compress()
 ; return 0; }
 EOF
-if { (eval echo configure:8097: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8096: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8122,7 +8121,7 @@ if test "$SYSTEM_JPEG" = 1; then
   SYSTEM_JPEG= 
 else
   cat > conftest.$ac_ext <<EOF
-#line 8126 "configure"
+#line 8125 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 	#include <sys/types.h>
@@ -8136,7 +8135,7 @@ else
 	}
 	
 EOF
-if { (eval echo configure:8140: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:8139: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   SYSTEM_JPEG=1
 else
@@ -8174,16 +8173,16 @@ if test "$ZLIB_DIR" = no; then
     SYSTEM_ZLIB=
 else
     echo $ac_n "checking "for zlib.h"""... $ac_c" 1>&6
-echo "configure:8178: checking "for zlib.h"" >&5
+echo "configure:8177: checking "for zlib.h"" >&5
     cat > conftest.$ac_ext <<EOF
-#line 8180 "configure"
+#line 8179 "configure"
 #include "confdefs.h"
 #include "zlib.h"
 int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:8187: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:8186: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   result="yes" SYSTEM_ZLIB=1
 else
@@ -8197,7 +8196,7 @@ rm -f conftest*
 fi
 if test "$SYSTEM_ZLIB" = 1; then
     echo $ac_n "checking for gzread in -lz""... $ac_c" 1>&6
-echo "configure:8201: checking for gzread in -lz" >&5
+echo "configure:8200: checking for gzread in -lz" >&5
 ac_lib_var=`echo z'_'gzread | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8205,7 +8204,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lz $ZLIB_LIBS $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8209 "configure"
+#line 8208 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8216,7 +8215,7 @@ int main() {
 gzread()
 ; return 0; }
 EOF
-if { (eval echo configure:8220: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8219: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8262,7 +8261,7 @@ if test "$PNG_DIR" = no; then
     SYSTEM_PNG=
 else
     echo $ac_n "checking for png_get_valid in -lpng""... $ac_c" 1>&6
-echo "configure:8266: checking for png_get_valid in -lpng" >&5
+echo "configure:8265: checking for png_get_valid in -lpng" >&5
 ac_lib_var=`echo png'_'png_get_valid | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8270,7 +8269,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpng $PNG_LIBS $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8274 "configure"
+#line 8273 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8281,7 +8280,7 @@ int main() {
 png_get_valid()
 ; return 0; }
 EOF
-if { (eval echo configure:8285: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8284: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8309,7 +8308,7 @@ if test "$SYSTEM_PNG" = 1; then
   SYSTEM_PNG= 
 else
   cat > conftest.$ac_ext <<EOF
-#line 8313 "configure"
+#line 8312 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 	#include <sys/types.h>
@@ -8323,7 +8322,7 @@ else
 	}
 	
 EOF
-if { (eval echo configure:8327: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:8326: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   SYSTEM_PNG=1
 else
@@ -8367,10 +8366,10 @@ CFLAGS="$CFLAGS -I${FULLCIRCLE_DIR}"
 LDFLAGS="$LDFLAGS -L${FULLCIRCLE_DIR}"
 
 echo $ac_n "checking "for FC_Initialize in -ltalkback"""... $ac_c" 1>&6
-echo "configure:8371: checking "for FC_Initialize in -ltalkback"" >&5;
+echo "configure:8370: checking "for FC_Initialize in -ltalkback"" >&5;
 LIBS="-ltalkback $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8374 "configure"
+#line 8373 "configure"
 #include "confdefs.h"
 
 	#include "fullcircle.h"
@@ -8382,7 +8381,7 @@ FC_Initialize();
         
 ; return 0; }
 EOF
-if { (eval echo configure:8386: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8385: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   FULLCIRCLE_LIB="-ltalkback $FULLCIRCLE_LIB" result="yes"
 else
@@ -8409,7 +8408,7 @@ if test "${with_pthreads+set}" = set; then
   withval="$with_pthreads"
   if test "$withval" = "yes"; then
 	    echo $ac_n "checking for pthread_attr_init in -lpthread""... $ac_c" 1>&6
-echo "configure:8413: checking for pthread_attr_init in -lpthread" >&5
+echo "configure:8412: checking for pthread_attr_init in -lpthread" >&5
 ac_lib_var=`echo pthread'_'pthread_attr_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8417,7 +8416,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpthread  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8421 "configure"
+#line 8420 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8428,7 +8427,7 @@ int main() {
 pthread_attr_init()
 ; return 0; }
 EOF
-if { (eval echo configure:8432: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8431: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8451,7 +8450,7 @@ fi
             if test "x$ac_cv_lib_pthread_pthread_attr_init" = "xno" -a \
                     "x$ac_cv_lib_c_r_gethostbyname_r" = "xno"; then
 	      echo $ac_n "checking for pthread_attr_init in -lc_r""... $ac_c" 1>&6
-echo "configure:8455: checking for pthread_attr_init in -lc_r" >&5
+echo "configure:8454: checking for pthread_attr_init in -lc_r" >&5
 ac_lib_var=`echo c_r'_'pthread_attr_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8459,7 +8458,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lc_r  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8463 "configure"
+#line 8462 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8470,7 +8469,7 @@ int main() {
 pthread_attr_init()
 ; return 0; }
 EOF
-if { (eval echo configure:8474: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8473: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8541,13 +8540,13 @@ else
 fi
 
 echo $ac_n "checking "for PR_GetCurrentThread in -lnspr3"""... $ac_c" 1>&6
-echo "configure:8545: checking "for PR_GetCurrentThread in -lnspr3"" >&5
+echo "configure:8544: checking "for PR_GetCurrentThread in -lnspr3"" >&5
 LIBS="-lnspr3 $NSPR_LIBS $LIBS"
 if test "$cross_compiling" = yes; then
   _NSPR_NEEDS_THREAD_LIB=1 result="no" 
 else
   cat > conftest.$ac_ext <<EOF
-#line 8551 "configure"
+#line 8550 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 	#include <nspr.h>
@@ -8557,7 +8556,7 @@ else
 	}
 	
 EOF
-if { (eval echo configure:8561: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:8560: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   NSPR_LIBS="-lnspr3 $NSPR_LIBS" result="yes"
 else
@@ -8578,7 +8577,7 @@ LIBS=$_SAVE_LIBS
 case "$target" in
 *-*-solaris*) 
 	echo $ac_n "checking for pthread_attr_init in -lpthread""... $ac_c" 1>&6
-echo "configure:8582: checking for pthread_attr_init in -lpthread" >&5
+echo "configure:8581: checking for pthread_attr_init in -lpthread" >&5
 ac_lib_var=`echo pthread'_'pthread_attr_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8586,7 +8585,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpthread  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8590 "configure"
+#line 8589 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8597,7 +8596,7 @@ int main() {
 pthread_attr_init()
 ; return 0; }
 EOF
-if { (eval echo configure:8601: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8600: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8619,7 +8618,7 @@ fi
  ;;
 *-*-linux*) 
 	echo $ac_n "checking for pthread_attr_init in -lpthread""... $ac_c" 1>&6
-echo "configure:8623: checking for pthread_attr_init in -lpthread" >&5
+echo "configure:8622: checking for pthread_attr_init in -lpthread" >&5
 ac_lib_var=`echo pthread'_'pthread_attr_init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8627,7 +8626,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpthread  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8631 "configure"
+#line 8630 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8638,7 +8637,7 @@ int main() {
 pthread_attr_init()
 ; return 0; }
 EOF
-if { (eval echo configure:8642: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8641: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8661,13 +8660,13 @@ fi
 esac
 
 echo $ac_n "checking "for PR_GetCurrentThread in -lnspr3 with thread lib"""... $ac_c" 1>&6
-echo "configure:8665: checking "for PR_GetCurrentThread in -lnspr3 with thread lib"" >&5
+echo "configure:8664: checking "for PR_GetCurrentThread in -lnspr3 with thread lib"" >&5
     LIBS="-lnspr3 $NSPR_LIBS $LIBS"
     if test "$cross_compiling" = yes; then
   MISSING_NSPR="$MISSING_NSPR -lnspr3" result="no" 
 else
   cat > conftest.$ac_ext <<EOF
-#line 8671 "configure"
+#line 8670 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 	#include <nspr.h>
@@ -8677,7 +8676,7 @@ else
 	}
 	
 EOF
-if { (eval echo configure:8681: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:8680: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   NSPR_LIBS="-lnspr3 $NSPR_LIBS" result="yes"
 else
@@ -8695,7 +8694,7 @@ fi
 
 
 echo $ac_n "checking for PL_CreateOptState in -lplc3""... $ac_c" 1>&6
-echo "configure:8699: checking for PL_CreateOptState in -lplc3" >&5
+echo "configure:8698: checking for PL_CreateOptState in -lplc3" >&5
 ac_lib_var=`echo plc3'_'PL_CreateOptState | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8703,7 +8702,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lplc3 $NSPR_LIBS $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8707 "configure"
+#line 8706 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8714,7 +8713,7 @@ int main() {
 PL_CreateOptState()
 ; return 0; }
 EOF
-if { (eval echo configure:8718: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8717: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8736,7 +8735,7 @@ MISSING_NSPR="$MISSING_NSPR -lplc3"
 fi
 
 echo $ac_n "checking for PL_GetEvent in -lplds3""... $ac_c" 1>&6
-echo "configure:8740: checking for PL_GetEvent in -lplds3" >&5
+echo "configure:8739: checking for PL_GetEvent in -lplds3" >&5
 ac_lib_var=`echo plds3'_'PL_GetEvent | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -8744,7 +8743,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lplds3 $NSPR_LIBS $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 8748 "configure"
+#line 8747 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -8755,7 +8754,7 @@ int main() {
 PL_GetEvent()
 ; return 0; }
 EOF
-if { (eval echo configure:8759: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:8758: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -8822,7 +8821,7 @@ then
 # Extract the first word of "makedepend", so it can be a program name with args.
 set dummy makedepend; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:8826: checking for $ac_word" >&5
+echo "configure:8825: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_SYSTEM_MAKEDEPEND'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -8849,6 +8848,7 @@ if test -n "$SYSTEM_MAKEDEPEND"; then
 else
   echo "$ac_t""no" 1>&6
 fi
+
 
 
 
@@ -8909,9 +8909,9 @@ fi
 fi # $no_x
 
 if test "$MISSING_NSPR"; then
-    { echo "configure: error: Could not find the following nspr libraries or could not run sample program: $MISSING_NSPR" 1>&2; exit 1; };
+   { echo "configure: error: Could not find the following nspr libraries or could not run sample program: $MISSING_NSPR" 1>&2; exit 1; };
 else
-	MOZ_BUILD_NSPR=
+   MOZ_NATIVE_NSPR=1
 fi
 
 # netlib stuff
@@ -9009,37 +9009,43 @@ for lib_arg in $NSPR_LIBS $TK_LIBS; do
 done
 
 
-cat >> confdefs.h <<\EOF
-#define MOZILLA_RPM_NSPR_OPTIMIZE 1
-EOF
-
-cat >> confdefs.h <<\EOF
-#define MOZILLA_RPM_PREFIX 1
-EOF
-
-cat >> confdefs.h <<\EOF
-#define MOZILLA_RPM_RELEASE 1
-EOF
-
-cat >> confdefs.h <<\EOF
-#define MOZILLA_RPM_SEAMONKEY_OPTIMIZE 1
-EOF
-
-cat >> confdefs.h <<\EOF
-#define MOZILLA_RPM_TMP 1
-EOF
-
-cat >> confdefs.h <<\EOF
-#define MOZILLA_RPM_VERSION 1
-EOF
+MOZ_RPM_NSPR_OPTIMIZE="BUILD_OPT=1"
+MOZ_RPM_PREFIX="/usr"
+MOZ_RPM_RELEASE="SeaMonkey_M4_BRANCH_19990409"
+MOZ_RPM_SEAMONKEY_OPTIMIZE="--disable-debug"
+MOZ_RPM_TMP="/tmp"
+MOZ_RPM_VERSION="5.0"
 
 
-MOZILLA_RPM_NSPR_OPTIMIZE="BUILD_OPT=1"
-MOZILLA_RPM_PREFIX="/usr"
-MOZILLA_RPM_RELEASE="SeaMonkey_M4_BRANCH_19990409"
-MOZILLA_RPM_SEAMONKEY_OPTIMIZE="--disable-debug"
-MOZILLA_RPM_TMP="/tmp"
-MOZILLA_RPM_VERSION="5.0"
+
+
+
+
+
+
+
+
+MOZ_NSPRENV_USE_PTHREADS=1
+
+if test "$MOZ_DEBUG"
+then
+  MOZ_NSPRENV_BUILD_OPT=
+else
+  MOZ_NSPRENV_BUILD_OPT=1
+fi
+
+if test "$GNU_CC"
+then
+  MOZ_NSPRENV_NS_USE_GCC=1
+  MOZ_NSPRENV_NS_USE_NATIVE=
+else
+  MOZ_NSPRENV_NS_USE_NATIVE=1
+  MOZ_NSPRENV_NS_USE_GCC=
+fi
+
+MOZ_NSPRENV_MOZILLA_CLIENT=1
+MOZ_NSPRENV_NO_MDUPDATE=1
+
 
 
 
@@ -9291,7 +9297,6 @@ s%@MOZ_INSURE_EXCLUDE_DIRS@%$MOZ_INSURE_EXCLUDE_DIRS%g
 s%@MOZ_INSURIFYING@%$MOZ_INSURIFYING%g
 s%@MOZ_MAIL_NEWS@%$MOZ_MAIL_NEWS%g
 s%@MOZ_BUILD_XPFE@%$MOZ_BUILD_XPFE%g
-s%@MOZ_BUILD_NSPR@%$MOZ_BUILD_NSPR%g
 s%@MOZ_EDITOR@%$MOZ_EDITOR%g
 s%@MOZ_BRPROF@%$MOZ_BRPROF%g
 s%@NEW_CLIPBOARD_SUPPORT@%$NEW_CLIPBOARD_SUPPORT%g
@@ -9320,6 +9325,7 @@ s%@PNG_LIBS@%$PNG_LIBS%g
 s%@NSPR_INCLUDE_DIR@%$NSPR_INCLUDE_DIR%g
 s%@NSPR_CFLAGS@%$NSPR_CFLAGS%g
 s%@NSPR_LIBS@%$NSPR_LIBS%g
+s%@MOZ_NATIVE_NSPR@%$MOZ_NATIVE_NSPR%g
 s%@WRAP_MALLOC_CFLAGS@%$WRAP_MALLOC_CFLAGS%g
 s%@WRAP_MALLOC_LIB@%$WRAP_MALLOC_LIB%g
 s%@MKSHLIB@%$MKSHLIB%g
@@ -9332,12 +9338,18 @@ s%@MODULAR_NETLIB@%$MODULAR_NETLIB%g
 s%@STANDALONE_IMAGE_LIB@%$STANDALONE_IMAGE_LIB%g
 s%@OS_TARGET@%$OS_TARGET%g
 s%@LIBS_PATH@%$LIBS_PATH%g
-s%@MOZILLA_RPM_NSPR_OPTIMIZE@%$MOZILLA_RPM_NSPR_OPTIMIZE%g
-s%@MOZILLA_RPM_PREFIX@%$MOZILLA_RPM_PREFIX%g
-s%@MOZILLA_RPM_RELEASE@%$MOZILLA_RPM_RELEASE%g
-s%@MOZILLA_RPM_SEAMONKEY_OPTIMIZE@%$MOZILLA_RPM_SEAMONKEY_OPTIMIZE%g
-s%@MOZILLA_RPM_TMP@%$MOZILLA_RPM_TMP%g
-s%@MOZILLA_RPM_VERSION@%$MOZILLA_RPM_VERSION%g
+s%@MOZ_RPM_NSPR_OPTIMIZE@%$MOZ_RPM_NSPR_OPTIMIZE%g
+s%@MOZ_RPM_PREFIX@%$MOZ_RPM_PREFIX%g
+s%@MOZ_RPM_RELEASE@%$MOZ_RPM_RELEASE%g
+s%@MOZ_RPM_SEAMONKEY_OPTIMIZE@%$MOZ_RPM_SEAMONKEY_OPTIMIZE%g
+s%@MOZ_RPM_TMP@%$MOZ_RPM_TMP%g
+s%@MOZ_RPM_VERSION@%$MOZ_RPM_VERSION%g
+s%@MOZ_NSPRENV_USE_PTHREADS@%$MOZ_NSPRENV_USE_PTHREADS%g
+s%@MOZ_NSPRENV_BUILD_OPT@%$MOZ_NSPRENV_BUILD_OPT%g
+s%@MOZ_NSPRENV_NS_USE_GCC@%$MOZ_NSPRENV_NS_USE_GCC%g
+s%@MOZ_NSPRENV_NO_MDUPDATE@%$MOZ_NSPRENV_NO_MDUPDATE%g
+s%@MOZ_NSPRENV_NS_USE_NATIVE@%$MOZ_NSPRENV_NS_USE_NATIVE%g
+s%@MOZ_NSPRENV_MOZILLA_CLIENT@%$MOZ_NSPRENV_MOZILLA_CLIENT%g
 
 CEOF
 EOF
