Bug 420933: outparams checker, r=bsmedberg, a=bsmedberg

diff --git a/xpcom/tests/static-checker/Makefile.in b/xpcom/tests/static-checker/Makefile.in
--- a/xpcom/tests/static-checker/Makefile.in
+++ b/xpcom/tests/static-checker/Makefile.in
@@ -41,6 +41,10 @@ topsrcdir = @top_srcdir@
 srcdir = @srcdir@
 VPATH = @srcdir@
 
+# MAKE_DIRS: List of directories to build while looping over directories.
+MAKE_DIRS               += $(MDDEPDIR)
+GARBAGE_DIRS            += $(MDDEPDIR)
+
 include $(DEPTH)/config/autoconf.mk
 
 STATIC_FAILURE_TESTCASES = \
@@ -50,17 +54,54 @@ STATIC_FAILURE_TESTCASES = \
   TestStackTemplate.cpp \
   $(NULL)
 
+OUTPARAMS_FAILURE_TESTCASES = \
+  e1.cpp \
+  e2.cpp \
+  e3.cpp \
+  e4.cpp \
+  e5.cpp \
+  e6.cpp \
+  e7.cpp \
+  e8.cpp \
+  e9.cpp \
+  e10.cpp \
+  e11.cpp \
+  $(NULL)
+
+OUTPARAMS_PASS_TESTCASES = \
+  o1.cpp \
+  o2.cpp \
+  o3.cpp \
+  o4.cpp \
+  o5.cpp \
+  o6.cpp \
+  o7.cpp \
+  o8.cpp \
+  o9.cpp \
+  o10.cpp \
+  $(NULL)
+
 include $(topsrcdir)/config/rules.mk
 
 # We want to compile each file and invert the result to ensure that
 # compilation failed.
-check:: $(STATIC_FAILURE_TESTCASES:.cpp=.s-fail)
+check:: $(STATIC_FAILURE_TESTCASES:.cpp=.s-fail) \
+  $(OUTPARAMS_FAILURE_TESTCASES:.cpp=.s-fail) $(OUTPARAMS_PASS_TESTCASES:.cpp=.s-pass)
 
 %.s-fail: %.cpp Makefile Makefile.in $(DEHYDRA_SCRIPTS)
 	@printf "Compiling $(<F) to check that the static-analysis script is checking properly..."
-	@if $(CCC) $(OUTOPTION)/dev/null -S $(COMPILE_CXXFLAGS) $(_VPATH_SRCS) >$(*F).errlog 2>&1; then \
+	@if $(CCC) -Werror $(OUTOPTION)/dev/null -S $(COMPILE_CXXFLAGS) $(_VPATH_SRCS) >$(*F).errlog 2>&1; then \
 	  printf "fail:\nerror: compilation of $(<F) succeeded. It shouldn't have!\n"; \
 	  exit 1; \
 	else \
 	  printf "ok.\n"; \
+	fi
+
+%.s-pass: %.cpp Makefile Makefile.in $(DEHYDRA_SCRIPTS)
+	@printf "Compiling $(<F) to check that the static-analysis script is checking properly..."
+	@if $(CCC) $(OUTOPTION)/dev/null -S $(COMPILE_CXXFLAGS) $(_VPATH_SRCS) >$(*F).errlog 2>&1; then \
+	  printf "ok.\n"; \
+	else \
+	  printf "fail:\nerror: compilation of $(<F) failed. It shouldn't have!\n"; \
+	  exit 1; \
 	fi
