Bug 1597903 - Add an error message when differences are found in diffoscope. r=froydnj
Differential Revision: https://phabricator.services.mozilla.com/D54068

diff --git a/taskcluster/docker/diffoscope/get_and_diffoscope b/taskcluster/docker/diffoscope/get_and_diffoscope
--- a/taskcluster/docker/diffoscope/get_and_diffoscope
+++ b/taskcluster/docker/diffoscope/get_and_diffoscope
@@ -50,6 +50,12 @@ esac
 # care about the builds being 100% identical).
 POST=true
 
+fail() {
+	set +x
+	echo "TEST-UNEXPECTED-FAIL | Builds differ. See the diff.html or diff.txt artifact"
+	exit 1
+}
+
 for option; do
 	case "$option" in
 	--unpack)
@@ -61,7 +67,7 @@ for option; do
 		done
 		;;
 	--fail)
-		POST="exit 1"
+		POST="fail"
 		;;
 	*)
 		echo "Unsupported option: $option" >&2
