Make configure fail if one or more required binaries or perl modules are missing. Bug #272690 r=bsmedberg

diff --git a/webtools/bonsai/configure b/webtools/bonsai/configure
--- a/webtools/bonsai/configure
+++ b/webtools/bonsai/configure
@@ -523,10 +523,12 @@ fi
 
 PERL_VERSION=5.006
 
-# Extract the first word of "perl perl5", so it can be a program name with args.
-set dummy perl perl5; ac_word=$2
+for ac_prog in $PERL perl5 perl
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:530: checking for $ac_word" >&5
+echo "configure:532: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -558,8 +560,11 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+test -n "$PERL" && break
+done
+
 echo $ac_n "checking for minimum required perl version >= $PERL_VERSION""... $ac_c" 1>&6
-echo "configure:563: checking for minimum required perl version >= $PERL_VERSION" >&5
+echo "configure:568: checking for minimum required perl version >= $PERL_VERSION" >&5
 _perl_version=`PERL_VERSION=$PERL_VERSION $PERL -e 'print "$]"; if ($] >= $ENV{PERL_VERSION}) { exit(0); } else { exit(1); }' 2>&5`
 _perl_res=$?
 echo "$ac_t""$_perl_version" 1>&6
@@ -569,7 +574,7 @@ if test "$_perl_res" != 0; then
 fi
 
 echo $ac_n "checking for full perl installation""... $ac_c" 1>&6
-echo "configure:573: checking for full perl installation" >&5
+echo "configure:578: checking for full perl installation" >&5
 _perl_archlib=`$PERL -e 'use Config; if ( -d $Config{archlib} ) { exit(0); } else { exit(1); }' 2>&5`
 _perl_res=$?
 if test "$_perl_res" != 0; then
@@ -579,37 +584,10 @@ else
     echo "$ac_t""yes" 1>&6    
 fi
 
-
-  echo $ac_n "checking for perl DBD::mysql module""... $ac_c" 1>&6
-echo "configure:585: checking for perl DBD::mysql module" >&5
-  $PERL -w -c -e 'use DBD::mysql' 2>/dev/null; has_dbd=$?
-  if test "x$has_dbd" = "x0" ; then
-     echo "$ac_t""yes" 1>&6
-     :
-  else
-     echo "$ac_t""no" 1>&6
-     echo "*** the perl MySQL module (DBD::mysql) could not be found"
-     :
-  fi
-
-
-  echo $ac_n "checking for perl Date::Parse module""... $ac_c" 1>&6
-echo "configure:598: checking for perl Date::Parse module" >&5
-  $PERL -w -c -e 'use Date::Parse' 2>/dev/null; has_dateparse=$?
-  if test "x$has_dateparse" = "x0" ; then
-     echo "$ac_t""yes" 1>&6
-     :
-  else
-     echo "$ac_t""no" 1>&6
-     echo "*** the perl Date::Parse module could not be found"
-     :
-  fi
-
-
 # Extract the first word of "co", so it can be a program name with args.
 set dummy co; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:613: checking for $ac_word" >&5
+echo "configure:591: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CO'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -644,7 +622,7 @@ fi
 # Extract the first word of "cvs", so it can be a program name with args.
 set dummy cvs; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:648: checking for $ac_word" >&5
+echo "configure:626: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CVS'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -676,10 +654,45 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+# Extract the first word of "cvsgraph", so it can be a program name with args.
+set dummy cvsgraph; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:661: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_CVSGRAPH'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$CVSGRAPH" in
+  /*)
+  ac_cv_path_CVSGRAPH="$CVSGRAPH" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_CVSGRAPH="$CVSGRAPH" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_CVSGRAPH="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+CVSGRAPH="$ac_cv_path_CVSGRAPH"
+if test -n "$CVSGRAPH"; then
+  echo "$ac_t""$CVSGRAPH" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
 # Extract the first word of "rlog", so it can be a program name with args.
 set dummy rlog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:683: checking for $ac_word" >&5
+echo "configure:696: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_RLOG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -714,7 +727,7 @@ fi
 # Extract the first word of "rcsdiff", so it can be a program name with args.
 set dummy rcsdiff; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:718: checking for $ac_word" >&5
+echo "configure:731: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_RCSDIFF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -747,10 +760,59 @@ else
 fi
 
 
+if test -z "$CO" -o -z "$CVS" -o -z "$RLOG" -o -z "$RCSDIFF"; then
+   { echo "configure: error: Missing one or more required binaries." 1>&2; exit 1; }
+fi
 
 
 
 
+
+for ac_mod in  \
+	CGI::Carp \
+	DBD::mysql \
+	DBI \
+	Date::Format \
+	Date::Parse \
+	File::Basename \
+	File::Path \
+	Mail::Internet \
+	Mail::Mailer \
+	Time::Local \
+; do
+       echo $ac_n "checking "for perl $ac_mod..."""... $ac_c" 1>&6
+echo "configure:785: checking "for perl $ac_mod..."" >&5
+    ac_mod_name=`echo $ac_mod | tr ':' '_'`
+    if eval "test \"`echo '$''{'ac_cv_perl_$ac_mod_name'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+     $PERL -w -c -e "use $ac_mod;" 2>/dev/null
+        ac_has_mod=$?
+        if test "$ac_has_mod" = "0"; then
+            eval "ac_cv_perl_$ac_mod_name=yes"
+        else
+            eval "ac_cv_perl_$ac_mod_name=no"
+        fi
+    
+fi
+
+    if eval "test \"`echo '$ac_cv_perl_'$ac_mod_name`\" = yes"; then
+        echo "$ac_t""yes" 1>&6
+                   ac_tr_func=HAVE_`echo $ac_func | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' | tr ':' '_'` 
+                cat >> confdefs.h <<EOF
+#define $ac_tr_func 1
+EOF
+ 
+    else
+        echo "$ac_t""no" 1>&6
+        _missing_perl_mod=1
+    fi
+done
+
+
+if test -n "$_missing_perl_mod"; then
+   { echo "configure: error: Missing one or more required Perl modules." 1>&2; exit 1; }
+fi
 
 trap '' 1 2 15
 cat > confcache <<\EOF
@@ -918,6 +980,7 @@ s%@mandir@%$mandir%g
 s%@PERL@%$PERL%g
 s%@CO@%$CO%g
 s%@CVS@%$CVS%g
+s%@CVSGRAPH@%$CVSGRAPH%g
 s%@RLOG@%$RLOG%g
 s%@RCSDIFF@%$RCSDIFF%g
 
