Bug 1766646 - Vendor libwebrtc from 8644f2b763
Upstream commit: https://webrtc.googlesource.com/src/+/8644f2b7632cff5e46560c2f5cf7c0dc071aa32d
    Revert "Split peer_connection_integrationtest.cc into pieces"

    This reverts commit cae4656d4a7439e25160ff4d94e50949ff87cebe.

    Reason for revert: Breaks downstream build (missing INSTANTIATE_TEST_SUITE_P in pc/data_channel_integrationtest.cc).

    Original change's description:
    > Split peer_connection_integrationtest.cc into pieces
    >
    > This creates two integration tests: One for datachannel, the other
    > for every test that is not datachannel.
    >
    > It separates out the common framework to a new file in pc/test.
    > Also applies some fixes to IWYU.
    >
    > Bug: None
    > Change-Id: I919def1c360ffce205c20bec2d864aad9b179c3a
    > Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/207060
    > Reviewed-by: Henrik Boström <hbos@webrtc.org>
    > Commit-Queue: Harald Alvestrand <hta@webrtc.org>
    > Cr-Commit-Position: refs/heads/master@{#33244}

    TBR=hbos@webrtc.org,hta@webrtc.org

    # Not skipping CQ checks because original CL landed > 1 day ago.

    No-Try: True
    Bug: None
    Change-Id: I7dbedd3256cb7ff47eb5f8cd46c7c044ed0aa1e0
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/207283
    Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
    Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
    Cr-Commit-Position: refs/heads/master@{#33255}

diff --git a/third_party/libwebrtc/tools_webrtc/iwyu/apply-iwyu b/third_party/libwebrtc/tools_webrtc/iwyu/apply-iwyu
--- a/third_party/libwebrtc/tools_webrtc/iwyu/apply-iwyu
+++ b/third_party/libwebrtc/tools_webrtc/iwyu/apply-iwyu
@@ -15,48 +15,28 @@ FILE=$1
 # the following variable to "yes". This is a style guide violation.
 REMOVE_CC_INCLUDES=no
 
-if [ ! -f $FILE ]; then
-  # See if we have the root name of a .cc/.h pair
-  if [ ! -f $FILE.h ]; then
-    echo "$FILE.h not found"
-    exit 1
-  fi
-  FILE_H=$FILE.h
-  if [ ! -f $FILE.cc ]; then
-    echo "$FILE.cc not found"
-    exit 1
-  fi
-  FILE_CC=$FILE.cc
-else
-  # Exact file, no .h file
-  FILE_CC=$FILE
-  FILE_H=""
+if [ ! -f $FILE.h ]; then
+   echo "$FILE.h not found"
+   exit 1
 fi
 
-iwyu -Xiwyu --no_fwd_decls -D__X86_64__  -DWEBRTC_POSIX -I . \
-  -I third_party/abseil-cpp \
-  -I third_party/googletest/src/googlemock/include \
-  -I third_party/googletest/src/googletest/include \
-  $FILE_CC |& fix_include || echo "Some files modified"
+if [ ! -f $FILE.cc ]; then
+   echo "$FILE.cc not found"
+   exit 1
+fi 
+
+iwyu -Xiwyu --no_fwd_decls -D__X86_64__  -DWEBRTC_POSIX -I . -I third_party/abseil-cpp $FILE.cc |& fix_include || echo "Some files modified"
 
 if [ $REMOVE_CC_INCLUDES == "yes" ]; then
-  if [ -n "$FILE_H" ]; then
-    # Don't include in .cc what's already included in .h
-    grep ^#include $FILE_H | grep -v -f - $FILE_CC > $FILE_CC.new
-  else
-    cp $FILE_CC $FILE_CC.new
-  fi
-  # Don't include stuff on the banlist
-  grep -v -f tools_webrtc/iwyu/iwyu-filter-list $FILE_CC.new > $FILE_CC
+  grep ^#include $FILE.h | grep -v -f - $FILE.cc > $FILE.ccnew
+  grep -v -f tools_webrtc/iwyu/iwyu-filter-list $FILE.ccnew > $FILE.cc
   rm $FILE.ccnew
 else
-  grep -v -f tools_webrtc/iwyu/iwyu-filter-list $FILE_CC > $FILE_CC.new
-  mv $FILE_CC.new $FILE_CC
+  grep -v -f tools_webrtc/iwyu/iwyu-filter-list $FILE.cc > $FILE.ccnew
+  mv $FILE.ccnew $FILE.cc
 fi
-if [ -n "$FILE_H" ]; then
-  grep -v -f tools_webrtc/iwyu/iwyu-filter-list $FILE_H > $FILE_H.new
-  mv $FILE_H.new $FILE_H
-fi
+grep -v -f tools_webrtc/iwyu/iwyu-filter-list $FILE.h > $FILE.hnew
+mv $FILE.hnew $FILE.h
 
 echo "Finished. Check diff, compile and git cl format before uploading."
 
