Bug 1627376 - Update cubeb-coreaudio to ea9e5aa. r=padenot
Pick commits:
- ea9e5aa: Implement a API to get `groupd_id` with special case handling (#69)
- d67d4d2: Revise prepush when deleting branch (#76)
- e5b0f97:  Stop test immediately when error happens (#77)
- 98e59e5: Migrate from travis-ci.org to travis-ci.com

Differential Revision: https://phabricator.services.mozilla.com/D69647

--HG--
extra : moz-landing-system : lando

diff --git a/third_party/rust/cubeb-coreaudio/.githooks/pre-push b/third_party/rust/cubeb-coreaudio/.githooks/pre-push
--- a/third_party/rust/cubeb-coreaudio/.githooks/pre-push
+++ b/third_party/rust/cubeb-coreaudio/.githooks/pre-push
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/bash -e
 
 # An example hook script to verify what is about to be pushed.  Called by "git
 # push" after it has checked the remote status, but before anything has been
@@ -16,8 +16,30 @@
 #
 #   <local ref> <local sha1> <remote ref> <remote sha1>
 
-remote="$1"
-url="$2"
+REMOTE="$1"
+URL="$2"
+
+PUSH_COMMAND=$(ps -ocommand= -p $PPID)
+
+IS_DESTRUCTIVE="\-\-delete|\-f"
+
+PROTECTED_BRANCH="trailblazer"
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+
+WILL_DELETE_PROTECTED_BRANCH=":$PROTECTED_BRANCH"
+
+if [[ $PUSH_COMMAND =~ $IS_DESTRUCTIVE ]]; then
+    if [ $CURRENT_BRANCH = $PROTECTED_BRANCH ] || [[ $PUSH_COMMAND =~ $PROTECTED_BRANCH ]]; then
+        echo "'$PROTECTED_BRANCH' cannot be deleted!"
+        exit 1
+    fi
+    exit 0
+fi
+
+if [[ $PUSH_COMMAND =~ $WILL_DELETE_PROTECTED_BRANCH ]]; then
+    echo "'$PROTECTED_BRANCH' cannot be deleted!"
+    exit 1
+fi
 
 cargo fmt -- --check || (echo "Please run 'cargo fmt'"; false);
 
