chore(workflows): コメントアウトされたコードを整理

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -375,27 +375,27 @@ jobs:
           cd ./floorp
           deno task build --release-build-after
 
-          # https://www.spinics.net/lists/git/msg391750.html
-          rsync -aL ../obj-artifact-build-output/dist/bin/ ../obj-artifact-build-output/dist/tmp__bin
-          rm -rf ../obj-artifact-build-output/dist/bin
-          mv ../obj-artifact-build-output/dist/tmp__bin ../obj-artifact-build-output/dist/bin
+          # # https://www.spinics.net/lists/git/msg391750.html
+          # rsync -aL ../obj-artifact-build-output/dist/bin/ ../obj-artifact-build-output/dist/tmp__bin
+          # rm -rf ../obj-artifact-build-output/dist/bin
+          # mv ../obj-artifact-build-output/dist/tmp__bin ../obj-artifact-build-output/dist/bin
 
-          if [ "${{inputs.platform}}" == "macOS-x64" ]; then
-            for patch_file in ./scripts/git-patches/patches/*.patch; do
-              for resource_dir in ../obj-artifact-build-output/dist/*.app/Contents/Resources; do
-                if patch --follow-symlinks --dry-run -d "$resource_dir" -p1 < "$patch_file"; then
-                  patch --follow-symlinks -d "$resource_dir" -p1 < "$patch_file"
-                else
-                  echo "Dry-run failed for $patch_file in $resource_dir" >&2
-                  exit 1
-                fi
-              done
-            done
-          else
-            git apply --reject ./scripts/git-patches/patches/*.patch --directory ../obj-artifact-build-output/dist/bin --unsafe-paths --check --apply
-          fi
+          # if [ "${{inputs.platform}}" == "macOS-x64" ]; then
+          #   for patch_file in ./scripts/git-patches/patches/*.patch; do
+          #     for resource_dir in ../obj-artifact-build-output/dist/*.app/Contents/Resources; do
+          #       if patch --follow-symlinks --dry-run -d "$resource_dir" -p1 < "$patch_file"; then
+          #         patch --follow-symlinks -d "$resource_dir" -p1 < "$patch_file"
+          #       else
+          #         echo "Dry-run failed for $patch_file in $resource_dir" >&2
+          #         exit 1
+          #       fi
+          #     done
+          #   done
+          # else
+          #   git apply --reject ./scripts/git-patches/patches/*.patch --directory ../obj-artifact-build-output/dist/bin --unsafe-paths --check --apply
+          # fi
 
-          cd ..
+          # cd ..
 
       - name: Replace RC Icon
         run: |
