Bug 234124 - RFE: Port the pluggable shell script API to FireFox/Thunderbird/Sunbird etc r=bryner@brianryner.com, sr=bryner@brianryner.com
Checking in patch for Roland Mainz <roland.mainz@nrubsig.org>

diff --git a/xpfe/bootstrap/mozilla.in b/xpfe/bootstrap/mozilla.in
--- a/xpfe/bootstrap/mozilla.in
+++ b/xpfe/bootstrap/mozilla.in
@@ -16,7 +16,7 @@
 # Reserved.
 #
 
-## $Id: mozilla.in,v 1.5 2004/02/05 20:32:05 cbiesinger%web.de Exp $
+## $Id: mozilla.in,v 1.6 2004/02/20 18:13:46 pkw%us.ibm.com Exp $
 ## 
 ## Usage:
 ##
@@ -29,33 +29,41 @@
 ## the mozilla-bin binary to work.
 ##
 
-moz_startstop_addon_scripts()
+moz_pis_startstop_scripts()
 {
   MOZ_USER_DIR="%MOZ_USER_DIR%"
+  # MOZ_PIS_ is the name space for "Mozilla Plugable Init Scripts"
+  # These variables and there meaning are specified in
+  # mozilla/xpfe/bootstrap/init.d/README
+  MOZ_PIS_API=2
+  MOZ_PIS_MOZBINDIR="${dist_bin}"
+  MOZ_PIS_SESSION_PID="$$"
+  MOZ_PIS_USER_DIR="${MOZ_USER_DIR}"
+  export MOZ_PIS_API MOZ_PIS_MOZBINDIR MOZ_PIS_SESSION_PID MOZ_PIS_USER_DIR
   
   case "${1}" in
     "start")
-      for i in ${dist_bin}/init.d/S* ${HOME}/${MOZ_USER_DIR}/init.d/S* ; do
-        if [ -r "${i}" ] ; then
-          case "${i}" in
-            *.sh) .  "${i}"         ;;
-            *)    sh "${i}" "start" ;;
+      for curr_pis in "${dist_bin}/init.d"/S* "${HOME}/${MOZ_USER_DIR}/init.d"/S* ; do
+        if [ -x "${curr_pis}" ] ; then
+          case "${curr_pis}" in
+            *.sh) .  "${curr_pis}"         ;;
+            *)       "${curr_pis}" "start" ;;
           esac
         fi
       done
       ;;
     "stop")
-      for i in ${HOME}/${MOZ_USER_DIR}/init.d/K* ${dist_bin}/init.d/K* ; do
-        if [ -r "${i}" ] ; then
-          case "${i}" in
-            *.sh) .  "${i}"        ;;
-            *)    sh "${i}" "stop" ;;
+      for curr_pis in "${HOME}/${MOZ_USER_DIR}/init.d"/K* "${dist_bin}/init.d"/K* ; do
+        if [ -x "${curr_pis}" ] ; then
+          case "${curr_pis}" in
+            *.sh) . "${curr_pis}"        ;;
+            *)      "${curr_pis}" "stop" ;;
           esac
         fi
       done
       ;;
     *)
-      echo 1>&2 "$0: Internal error in moz_startstop_addon_scripts."
+      echo 1>&2 "$0: Internal error in moz_pis_startstop_scripts."
       exit 1
       ;;
   esac
@@ -147,7 +155,7 @@ export MRE_HOME
 eval "set -- $moreargs"
 
 ## Start addon scripts
-moz_startstop_addon_scripts "start"
+moz_pis_startstop_scripts "start"
 
 if [ $debugging = 1 ]
 then
@@ -157,7 +165,7 @@ fi
 exitcode=$?
 
 ## Stop addon scripts
-moz_startstop_addon_scripts "stop"
+moz_pis_startstop_scripts "stop"
 
 exit $exitcode
 # EOF.
